### ISSUE TITLE
S3 Bucket Provisioning Failing

### ISSUE THREAD

**Issue by simsek97** [salesforce-misc/Data-Lake-for-Nonprofits#10]
**Describe the bug**
On step 5, while provisioning S3 buckets, this error is popping up. Could not provision the S3 buckets stack

**To Reproduce**
1. Deploy a new datalake.
2. Go to Step 5
3. The first line of action fails

**Expected behavior**
S3 buckets should be provisioned successfully.

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: 1.26.36

**Additional context**
This problem happens due to a policy change on S3. On April, 2023, the S3 team deployed a few updates in S3 to follow the best practices related to ACL and object ownership due to which we see a common error in the Cloudformation Stack while deploying an S3 bucket.
More information about S3 changes: 
https://aws.amazon.com/blogs/aws/heads-up-amazon-s3-security-changes-are-coming-in-april-of-2023/
More information about the issue:
https://guide.aws.dev/articles/ARehSZtzMGRvCxDbS5biqeQQ/cloudformation-creation-bucket-cannot-have-acls-set-with-objectownership-s-bucketownerenforced-setting

**Comment by jairollorente** [comment]
Alguna estimación de cuándo estará resuelto este problema?

**Comment by simsek97** [comment]
This issue has been fixed by the version v1.26.38. 
Keep in mind if you have unfinished deployments due to this issue, resuming them is not going to work even if you update the application with this version since we don't recopy the assets while resuming. In order to deploy a data lake with this version, you will need to start a new deployment.

**Comment by simsek97** [comment]
Closing this issue since it is resolved
