### ISSUE TITLE
Could not import Salesforce objects

### ISSUE THREAD

**Issue by GreenSaaSDev** [salesforce-misc/Data-Lake-for-Nonprofits#5]
Select a subset of the NPSP objects and two custom objects.  >100k records in 3 of the 10 object tables.  The error message returned does not aid in determining why the fetch failed.  **Are there more granular logs available?**

Oops, things did not go smoothly, we are unable to provision the data lake. This might be an intermittent problem. Wait for a few minutes and try again. If you continue to get this error, you can peek at the technical details and seek assistance from a solution implementor agency.
Failed to fetch

**Comment by simsek97** [comment]
Is it possible to share a screenshot related to the error? 
In general, every step has been logged using CloudWatch but if I can see a screenshot, it'd be more helpful to point to the right CloudWatch logs.

**Comment by GreenSaaSDev** [comment]
I reduced the number of objects, specifically removing Task from the extract and it was eventually successful.  The broader question is to what extent implementation teams have access to granular error logging (Field-Level Security issues, etc) that may pinpoint issues.
