### ISSUE TITLE
Data Import (sfimport) Failure 

### ISSUE THREAD

**Issue by GreenSaaSDev** [salesforce-misc/Data-Lake-for-Nonprofits#9]
**Describe the bug**
Import SF Data failed.  Through the Amplify application, it appears this is happening due to too many concurrent executions.  When running the Import directly through Step Functions it is failing due to SQL Setup failure

{
  "resourceType": "lambda",
  "resource": "invoke",
  "error": "Lambda.Unknown",
  "cause": "The cause could not be determined because Lambda did not return an error type. Returned payload: {\"errorMessage\":\"2023-05-12T00:48:46.092Z bff4ec05-f64d-40e0-b25a-1e4b73d10fe7 Task timed out after 60.02 seconds\"}"
}

**To Reproduce**
1. Go to Application in AWS Amplify
2. Click on Domain and Manage Data Lake
3. Enter RootKey
4. Go down to Latest Data Export and note the error
5. Run the sfimport directly from step functions and notice same error

**Expected behavior**
Expected that the application would pull the data into RDS

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by GreenSaaSDev** [comment]
I do see the SQLSetup having a default timeout of 60 seconds and it's likely this, I'm guessing, that is causing the failure.  Is that something I can change after the DataLake is set up?  and is this something that can be modifying in the build script to prevent such a low timeout interval from having to be modified later?

**Comment by simsek97** [comment]
The timeout you mentioned is configured for the Lambda functions. You can go to the said Lambda function on AWS console and update the timeout parameter under the Configuration tab.
